apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: application-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: applicationdeployment
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
           claimName: task-pv-claim
      containers:
      - name: writer-container
        image: namrathab/writer
        volumeMounts:
          - mountPath: "/folder"
            name: task-pv-storage
      - name: reader-container
        image: namrathab/reader
        volumeMounts:
          - mountPath: "/folder"
            name: task-pv-storage
